name: Daily Instagram Idea to Telegram

on:
  schedule:
    # Run once a day at 9:00 UTC (you can change this later)
    - cron: '0 9 * * *'
  workflow_dispatch: # allows manual trigger

jobs:
  generate_and_send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai python-telegram-bot

      - name: Run daily script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python daily_idea.py
